# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: themattrix/tox

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - python3.6 --version
          - pip3.6 --version
          - tox --version
          - pip2.7 install . --user
          - pip3.5 install . --user
          - pip3.6 install . --user
          - python3.6 -c "import numpy; print('numpy', numpy.__version__)"
          - python3.6 -c "import scipy; print('scipy', scipy.__version__)"
          - python2.7 -m unittest discover tests/ -v
          - python3.5 -m unittest discover tests/ -v
          - python3.6 -m unittest discover tests/ -v
