# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            python -m pip install --user -U flake8==3.7.1
            python -m flake8 --show-source euclid/ tests/


  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Run tests
          command: |
            python --version
            python -m pip install .[test] --user
            python -c "import numpy; print('numpy', numpy.__version__)"
            python -c "import scipy; print('scipy', scipy.__version__)"
            pytest

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6


workflows:
  version: 2
  test:
    jobs:
      - style-check
      - test-3.6:
          requires:
            - style-check
      - test-3.7:
          requires:
            - style-check
