# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            python -m pip install --progress-bar off --user -U flake8 flake8-black flake8-bugbear flake8-docstrings flake8-rst-docstrings pep8-naming flake8-isort
            python -m flake8 --show-source coxeter/
            # Ignore isort errors in tests that are due to ambiguity over whether or not coxeter is third party.
            python -m flake8 --extend-ignore=I001,I004 --show-source tests/


  test-3.8: &test-template
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Run tests
          command: |
            python --version
            python -m pip install .[test] --progress-bar off --user
            python -c "import numpy; print('numpy', numpy.__version__)"
            python -c "import scipy; print('scipy', scipy.__version__)"
            pytest

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  pypi_wheels: &pypi_wheels
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy dist and wheels
          command: |
            python -m pip install --progress-bar off --user -U flake8 flake8-black flake8-bugbear flake8-docstrings flake8-rst-docstrings pep8-naming flake8-isort
            python -m pip install .[test] --progress-bar off --user
            python -m flake8 --show-source coxeter/
            # Ignore isort errors in tests that are due to ambiguity over whether or not coxeter is third party.
            python -m flake8 --extend-ignore=I001,I004 --show-source tests/
            python -m pytest
            python --version
            python -m pip --version
            python -m pip install --progress-bar off --user -U twine wheel setuptools
            python -m twine --version
            python -m wheel version
            python setup.py sdist
            python setup.py bdist_wheel
            python -m twine upload --username vramasub --password ${PYPI_PASSWORD} dist/*

workflows:
  version: 2
  test:
    jobs:
      - style-check
      - test-3.8:
          requires:
            - style-check
      - test-3.7:
          requires:
            - style-check
      - test-3.6:
          requires:
            - style-check
  deploy:
    jobs:
      - pypi_wheels:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
